-- INSERT INTO topic (topic_title) VALUES 
-- ('Java'),
-- ('Bazy danych'),
-- ('Projektowanie aplikacji'),
-- ('Referring');

-- INSERT INTO subtopic(topic_id, subtopic_title) VALUES 
-- (1, 'Java'),
-- (1, 'Spring'),
-- (2, 'Bazy danych'),
-- (3, 'Projektowanie aplikacji'),
-- (4, 'Referring');

-- INSERT INTO question(subtopic_id, content, answerA, answerB, answerC, answerD, correct_answer, difficulty_level) VALUES
-- ('', '', '', '', '', '', '', '');
-- ('Jaka jest różnica między obiektem wartości (Value Object) a encją (Entity) w kontekście DDD?', 'VO jest niemutowalny (ang. immutable), a encja jest mutowalna (ang. mutable)', 'VO nie posiada identyfikatora a encja posiada', 'Cykl życia VO może zależeć od encji, ale cykl życia encji nie może zależeć od VO', 'Wszystkie odpowiedzi są poprawne', 'D', 'HARD', 'PROJEKTOWANIE_APLIKACJI'),
-- ('Który typ danych w Javie służy do przechowywania liczb całkowitych?', 'double', 'int', 'char', 'boolean', 'B', 'EASY', 'JAVA'),
-- ('Która pętla wykona się co najmniej raz niezależnie od warunku?', 'for', 'while', 'do-while', 'foreach', 'C', 'EASY', 'JAVA'),
-- ('Co oznacza słowo kluczowe new w Javie?', 'Tworzy nową zmienną', 'Tworzy nową klasę', 'Tworzy nowy obiekt', 'Usuwa obiekt', 'C', 'EASY', 'JAVA'),
-- ('Co oznacza słowo kluczowe final dla zmiennej w Javie?', 'Zmienna może zmieniać wartość tylko raz po każdej metodzie.', 'Zmienna nie może zostać ponownie przypisana po inicjalizacji.', 'Zmienna jest dostępna tylko w klasie.', 'Zmienna jest automatycznie statyczna.', 'B', 'EASY', 'JAVA'),
-- ('Która kolekcja w Javie przechowuje unikalne elementy?', 'List', 'ArrayList', 'Set', 'LinkedList', 'C', 'EASY', 'JAVA'),
-- ('Do czego służy adnotacja @Override?', 'Do tworzenia nowej klasy.', 'Do oznaczenia, że metoda nadpisuje metodę z klasy nadrzędnej lub interfejsu.', 'Do ukrywania metod przed innymi klasami.', 'Do automatycznego tworzenia getterów i setterów.', 'B', 'EASY', 'JAVA'),

-- === REFERRING ===
-- (5, 'Napastnik wcześniej już napomniany w zawodach nadmiernie fetuje zdobycie bramki (zakrywa twarz maską) po tym, jak udało mu się wyrównać wynik meczu. Jaką decyzje podejmie sędzia jeżeli uzna on wskazanie swojego asystenta, na podstawie którego bramka zostanie nieuznana z tytułu wcześniej zaistniałego spalonego?', '+', 'P', 'P + ++', 'S', 'C', 'MEDIUM'),
-- ('5', 'Obrońca wykonuje rzut wolny bezpośredni i podaje piłkę do bramkarza, który poślizgnął się na trawie i nie dotknie piłki. Następnie napastnik drużyny przeciwnej biegnie w kierunku piłki, więc ten sam obrońca wybija piłkę na rzut rożny i pozbawia przeciwnika realnej szansy na zdobycie bramki (DOGSO). Jaka jest właściwa decyzja?', 'P +', 'P ++', 'R', 'S', 'B', 'MEDIUM'),
-- ('5', 'Sędzia asystent podczas zawodów IV Ligi został zaatakowany przez kibica butelką rzuconą z trybun. Zespół sędziowski odczuwał niebezpieczeństwo kontynuowania zawodów. Jakie decyzje powinien podjąć sędzia?', 'Z', 'G', '++', 'S', 'A', 'MEDIUM'),
-- ('5', 'Dwóch zawodników gospodarzy zderzyło się z sobą, w tej samej akcji. Leżeli na boisku, a sędzia wezwał do nich pomoc medyczną. Jeden z nich, już po przerwaniu gry, zdążył wstać zanim ktokolwiek mu pomógł, więc nie miał kontaktu z masażystą. Przed wznowieniem gry sędzia:', 'pozostawi obu zawodników na boisku', 'usunie tylko jednego zawodnika razem z masażystą', 'usunie obu zawodników poza boisko', 'żadne z powyższych', 'A', 'EASY'),
-- ('5', 'Zawodnik, który ma zostać wymieniony, znajduje się po drugiej stronie pola gry, blisko linii bocznej. Po otrzymaniu od sędziego sygnału do opuszczenia pola gry w najbliższym punkcie linii bocznej, zawodnik powoli podchodzi do zawodnika rezerwowego, który znajduje się na linii środkowej. Jaka będzie decyzja sędziego?', 'G', 'P', 'B', '+', 'D', 'MEDIUM'),
-- ('5', 'Zawodnik gospodarzy zagrał piłkę do własnego bramkarza, a miało to miejsce wewnatrz pola karnego przeciwników. Bramkarz ewidentnie chciał silnie kopnąć piłkę, lecz skiksował i w wyniku tego złapał piłkę do rąk. Podaj decyzję.', 'G', 'B', 'P', 'S', 'B', 'EASY'),
-- ('5', 'Obrońca kopie piłkę do bramkarz (współpartnera). Po kopnięciu piłki, napastnik drużyny przeciwnej również goni piłkę, więc bramkarz wybiega poza pole karne i celowo dotyka ręką piłki. Jaka jest właściwa decyzja:', 'B ++', 'B +', 'B', 'P ++', 'C', 'MEDIUM'),
-- ('5', 'Sędzia omyłkowo skrócił II połowę meczu o 5 minut, przerywając statyczna akcję gości w środku pola. Zdenerwowany kapitan gości dobiegł do sędziego krzycząc: "co ty kurwa robisz? Jaki koniec?!" i odepchnął sędziego rękami w klatkę piersiową. Co postanowi sędzia, wiedząc, że ten kapitan miał już żółtą kartkę?', 'udzieli kapitanowi gości drugiej żółtej kartki i w konsekwencji czerwonej, a gre wznowi rzutem wolnym pośrednim', 'udzieli kapitanowi gości czerwonej kartki, a grę wznowi rzutem sędziowskim', 'udzieli kapitanowi gości czerwonej kartki, a grę wznowi rzutem wolnym bezpośrednim', 'udzieli kapitanowi gości drugiej żółtej kartki i w konsekwencji czerwonej, a gre wznowi rzutem wolnym bezpośrednim', 'B', 'MEDIUM'),
-- ('5', 'Zawodnik zamienił się funkcją z bramkarzempodczas gry nie informując o tym sędziego. Decyzja?', 'P +', 'G', 'G + +', 'B', 'C', 'MEDIUM');
-- ('', '', '', '', '', '', '', '');
